# Generated by Django 3.2.6 on 2021-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0002_auto_20210821_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UnConfirmed', 'UnConfirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Receieved', 'Receieved')], default='UnConfirmed', max_length=20),
        ),
    ]
