# Generated by Django 3.2.6 on 2021-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
