# Generated by Django 3.2.6 on 2021-08-20 11:42

import App_Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AddOns',
                'db_table': 'AddOns',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=App_Main.models.upload_category)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'DayTime',
                'db_table': 'DayTime',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'db_table': 'Variants',
            },
        ),
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150)),
                ('dish_picture', models.ImageField(blank=True, null=True, upload_to=App_Main.models.upload_image)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('dish_vat', models.IntegerField(default=0)),
                ('dish_tax', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('dish_category', models.ManyToManyField(blank=True, to='App_Main.Category')),
                ('dish_daytime', models.ManyToManyField(blank=True, to='App_Main.DayTime')),
            ],
            options={
                'verbose_name_plural': 'Dish',
                'db_table': 'Dish',
            },
        ),
    ]
